### ISSUE TITLE
Manually disabling a pulse timer fails

### ISSUE THREAD

**Issue by eode** [mozilla-iot/pulse-adapter#11]
I have a pulse timer that is turned on by a rule.  Even if I disable rules, I can't turn it off -- it must time out.

**Comment by eode** [comment]
This can be caused just by clicking to enable a pulse timer, then clicking to disable it again -- rules are not required.

**Comment by mrstegeman** [comment]
That's how the pulse is intended to work. Are you just needing a generic on/off switch?

**Comment by eode** [comment]
@mrstegeman No, I don't need a generic on/off switch -- more like the timed lights you have in a bathroom that go on when you come in, but that you can also manually shut off on your way out.

My main reason for this is to have one spot to turn the thing on/off, but that shuts off automatically when unused.  It doesn't seem too far from the base usage of the pulse timer.
