### ISSUE TITLE
Names can generate invalid IDs

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/pulse-adapter#6]
Since the name is essentially used as the thing ID, the user can mess things up. For instance, if a `/` is used in the name, the UI will not work for that device, as the URL path will end up being wrong.

An easy way around this is to hash the name, which is what we do for the weather adapter. However, that will cause users to have to remove and re-add their devices.

**Comment by dhylands** [comment]
We could also just substitute invalid characters with a dash (or an HTML escape), which would cause current ids to remain valid and would only affect the invalid ones. Presumably none of these exist yet.

**Comment by mrstegeman** [comment]
https://discourse.mozilla.org/t/remove-invalid-thing/40373
